### ISSUE TITLE
Add NIP-04 support

### ISSUE THREAD

**Issue by ArcadeCityMayor** [ArcadeLabsInc/arcade#137]
When clicking on a user profile and then the Message button, user should be able to send a NIP-04 DM.

NIP-04 DMs should show up in the same list of chat channels along with group chats, similar to Telegram.

**Comment by earonesty** [comment]
the module "private.ts" exports nip04 supporting sub() and send() functions

**Comment by ArcadeCityMayor** [comment]
Solved in #143
