### ISSUE TITLE
Add encrypted group chat

### ISSUE THREAD

**Issue by ArcadeCityMayor** [ArcadeLabsInc/arcade#151]
The big one! Let's figure out how to do this.

We can start with something simple, maybe Vishal's [NIP-38](https://github.com/nostr-protocol/nips/pull/59/files).

Later on we can experiment with new stuff like MLS or SimpleX etc., but for now let's figure out what an "MVP" version of this looks like.

**Comment by earonesty** [comment]
works now in my branch (you can create, join, send, receive)
