### ISSUE TITLE
Issues on Android

### ISSUE THREAD

**Issue by reyamir** [ArcadeLabsInc/arcade#190]
1. Can't load message in channel
![Screenshot_20230612-073739](https://github.com/ArcadeLabsInc/arcade/assets/123083837/c8f90801-819f-48b6-8c4c-828938103afa)
2. Some text don't display (fine in iOS)
![Screenshot_20230612-073615](https://github.com/ArcadeLabsInc/arcade/assets/123083837/fb18a71b-89ee-4a40-b921-b5547d6a2ff6)
3. Bottom tabs padding bottom a bit high (android)
![Screenshot_20230612-073507](https://github.com/ArcadeLabsInc/arcade/assets/123083837/b3dab01b-32cf-4b2c-af2e-60ee1fa89b9f)

**Comment by ArcadeCityMayor** [comment]
Ignore #1, that's a hardcoded placeholder

**Comment by ArcadeCityMayor** [comment]
Fixed in #193
