### ISSUE TITLE
Signup: Same username can be created

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#244]
1. Open signup
2. Enter username in username field eg "test"
3. Create user
4. User is created successfully
5. Logout and create user with same name "test"
6. User is created successfully

Actual: User with same should not be created 

Expected: https://github.com/ArcadeLabsInc/arcade/assets/5452850/77217d32-a7d3-4992-8766-ace6756472bc

**Comment by earonesty** [comment]
should be resolved.
