### ISSUE TITLE
Private channel:Invite: Already added contacts are appearing in the invite screen

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#259]
1. Login into the app
2. Go to channel page
3. Create private channel and go to invite screen
4. Add some contacts, user is redirected to channel chat screen
5. Now come again to invite screen 

AR: Already added users are appearing in the contact invite list, checkbox is missing for the contacts that are already invited
ER: Once users are added to the channel invited list they should not be invited again and check box should always appear in front of their name.
Video: https://quality.tinytake.com/msc/ODM4NDQxM18yMTY2MzYxNg

**Comment by earonesty** [comment]
solution:

store added contacts and any "observed contacts"  and exclude them

can also make a nice "members" list when clicking on the chat

**Comment by reyamir** [comment]
I'm working on it

**Comment by vikas1809** [comment]
Working fine https://github.com/ArcadeLabsInc/arcade/actions/runs/5466714629
