### ISSUE TITLE
Contacts: Sometimes profile icon is not loading for profiles

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#263]
1. Open contact list
2. Add some contact
3. Notice sometimes added contact do not show the profile icon
4. Not able to reproduce the exact steps but I get this issue many times.

![Profile icon](https://github.com/ArcadeLabsInc/arcade/assets/5452850/ccf37225-604f-4e68-a3c5-b5a5bba947a3)

**Comment by earonesty** [comment]
that icon means "public".   if you add a private contact it is not present.   i think its working ok.

**Comment by vikas1809** [comment]
But after refreshing those icons reappears, I'll record a video once i will able to reproduce it again.
