### ISSUE TITLE
Profile: Contact settings: "Use legacy, unblinded DM's" setting blur out when user enables "Hide this contact(private follow)" setting

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#265]
Open any profile
Go to contact settings
Enable "Hide this contact(private follow)" setting
Notice the "Use legacy, unblinded DM's" setting blur out

ER: "Use legacy, unblinded DM's" setting should remain as it is.

https://github.com/ArcadeLabsInc/arcade/assets/5452850/c4023819-4c00-4eea-94be-47570a39d6ac

**Comment by reyamir** [comment]
function is fine, but UI is a bit confuse, I will update it

**Comment by vikas1809** [comment]
Not fixed, reporting new

**Comment by reyamir** [comment]
oh I forgot push code for it

**Comment by reyamir** [comment]
instead of make toggle disabled, we should show a help text

**Comment by reyamir** [comment]
updated in #351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
