### ISSUE TITLE
Settings: Manage Relays:User is able to add "ws://" instead of "wss://" in the relay url

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#270]
1. Open settings->Manage Relays
2. Open add relay textbox
3. Try to add relay url as " ws://"

AR: Relay is successfully added
ER: Relay url should only accept "wss://" in url
Video/Screenshot: https://quality.tinytake.com/msc/ODM4OTEwNl8yMTY2OTYyNg

**Comment by reyamir** [comment]
some few relays only support `ws://`, I think it is fine
