### ISSUE TITLE
Settings: Manage Relays:  App get crashed when user sliding down the "Add custom relay" textbox

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#272]
1. Open settings->Manage Relays
2. Open add relay textbox
3. Click on relay url field, keyboard will open
4. Now slide down the textbox

AR: App get crashed
ER: App should not crashed , "Add custom relay" textbox should close
Video: https://quality.tinytake.com/msc/ODM4OTEyMV8yMTY2OTY0MQ

**Comment by reyamir** [comment]
can you help me retest it on latest build?, look like it is fixed

**Comment by reyamir** [comment]
ah ok, I got error now, fixing

**Comment by vikas1809** [comment]
Working fine on https://github.com/ArcadeLabsInc/arcade/actions/runs/5466714629
