### ISSUE TITLE
Profile: User is able to add black characters in username and bio

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#285]
1. Open update profile page
2. Add black characters in username and bio

AR: Username and bio are black which looks odd
ER: Profile should have username and bio appearing under Account
Video: https://quality.tinytake.com/msc/ODM5MzE2N18yMTY3NTEwNw

**Comment by reyamir** [comment]
updated

**Comment by vikas1809** [comment]
Fixed, Verified in latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5527270114
