### ISSUE TITLE
Direct message: Alert is missing when user tap on send button without entering anything

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#292]
1. Open direct message window
2. Tap on send icon without entering anything

AR: No alert is coming 
ER: There should be alert " Message cannot be empty"
Video: https://quality.tinytake.com/msc/ODM5MzIzMF8yMTY3NTE3MA

**Comment by earonesty** [comment]
this is good i think,  that message is weird

**Comment by vikas1809** [comment]
working fine on latest release: https://github.com/ArcadeLabsInc/arcade/actions/runs/5481856836
