### ISSUE TITLE
Cannot log in with valid nsec: mobx-state-tree error 

### ISSUE THREAD

**Issue by ArcadeCityMayor** [ArcadeLabsInc/arcade#297]
Looks like the error is with the `applySnapshot` line in the `loginWithNsec` function.

Generates this MST error. And also throws an incorrect alert. My nsec was fine, tested in another client, so it should not say I have an invalid key - it's a different kind of error.

![loginerror](https://github.com/ArcadeLabsInc/arcade/assets/14167547/9ab0e1eb-1051-434a-8181-2490ba38a8ca)

**Comment by earonesty** [comment]
this should fix it:

https://github.com/ArcadeLabsInc/arcade/actions/runs/5480289582?pr=252

**Comment by reyamir** [comment]
duplicate with https://github.com/ArcadeLabsInc/arcade/issues/302

**Comment by vikas1809** [comment]
Verified in latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5527270114
