### ISSUE TITLE
Channel: User is able to send chat with blank characters

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#301]
Not fixed, reporting new issue

_Originally posted by @vikas1809 in https://github.com/ArcadeLabsInc/arcade/issues/293#issuecomment-1624927131_

**Comment by reyamir** [comment]
I'll handle empty message like telegram, instead of using alert popup, only show send button if user enter valid message

**Comment by reyamir** [comment]
fixed in latest commit (new ui)

**Comment by vikas1809** [comment]
Working fine checked in : https://github.com/ArcadeLabsInc/arcade/actions/runs/5503699108
