### ISSUE TITLE
Channels got disappear if user logout and come again

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#304]
1. Login into the Arcade
2. Join some channels
3. Logout the app
4. Login again
5. Notice the joined channels disappear

https://github.com/ArcadeLabsInc/arcade/assets/5452850/4c16a36e-989e-49bd-9a85-1c62c82d61fb

**Comment by reyamir** [comment]
will fixed in #296

**Comment by vikas1809** [comment]
@reyamir  Still not fixed, can you please reopen it.
