### ISSUE TITLE
Channels: "Join" button should change to "Remove" once the channels is joined by the user

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#305]
1. Open channel list
2. Join any channel
3. Come back to channel list
4. Notice the join button remain as it is.

ER:  "Join" button should change to "Remove" once the channels is joined by the user

https://github.com/ArcadeLabsInc/arcade/assets/5452850/5fee23e2-d1af-40f7-95b9-e5efb14590b4

**Comment by reyamir** [comment]
will be updated in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
