### ISSUE TITLE
Home : Long Channel name overlaps with the invite icon at top left corner 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#306]
"1. Open the Arcade app on Android 
2. On homepage, tap on the hamburger menu 
3. Create a new private channel having long name 
4. On invite screen, check long name overlaps with the invite icon "

AR: Long Channel name overlaps with the invite icon 
ER: Long channel name should  be in ellipsis 
Video/Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMjY3M18yMTcwMTk1Nw

**Comment by reyamir** [comment]
fixed in latest commit, I guess
but for sure you can test it again

**Comment by vikas1809** [comment]
Fixed, Verified in latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5527270114
