### ISSUE TITLE
Create Account: Initially the 'About' text is showing for description field but after creating the account, the field displays as 'Bio' 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#307]
"1. Open the Arcade App on Android
2. Tap on the 'Create Account' Page and scroll down the page
3. Notice the 'About' text displays for description 
4. Fill in the details and open the App again
5. Notice the 'About' text gets replaced with the 'Bio' field for created account"

AR: Initially the 'About' text is showing for description field but after creating the account, the field displays as 'Bio'
ER: Same text should display on the 'Create Account' Page and after the account is created
Video/Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMjg2NV8yMTcwMjE2NA

**Comment by reyamir** [comment]
better use "About" for consistent across all nostr clients

**Comment by reyamir** [comment]
updated in #351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
