### ISSUE TITLE
Home: "Something went wrong" error message is appearing after accessing a particular group

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#308]
"1. Open the Arcade app on Android 
2. On the homepage, tap on the hamburger menu
3. Tap on the search icon.
4. Join some channels on the channels screen i.e.Permaculture
5. Notice the ""something went wrong"" error message is appearing "

AR: The "Something went wrong"  error message appears.
ER: The "Something went wrong"  error message should not appear.
Video/Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMzEwN18yMTcwMjQ2Nw

**Comment by reyamir** [comment]
fixed

**Comment by vikas1809** [comment]
Fixed, Verified in latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5527270114
