### ISSUE TITLE
"Invite screen :   Error message shown inappropriate while keeping the field blank in the ""Invite by pubkey"" modal box"

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#309]
"1. Open the Arcade app on Android 
2. On the homepage, tap on the hamburger menu
3. Create a new private channel
4. On Invite screen, add new contact by tapping ""+"" button
5. In Popup box, leave the field blank and tap on ""Add"" button
6. Check the error message ""pubkey/npub is invalid, please check again"" "

AR:Error message is not appropriate while keeping the field blank in the "Invite by pubkey" popup 
ER: Correct error message should display "Public key or npub can't be Blank" 
Video/Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMzE3OV8yMTcwMjU2OA

**Comment by reyamir** [comment]
fixed
