### ISSUE TITLE
New message screen :  Text copy instead of ""New private channel"" showing as ""New private group"

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#310]
"1. Open the Arcade app on Android 
2. On the homepage, tap on the ""+"" button 
3. New message screen will appear
4. Check the Button text copy ""New private group"" "

AR: Button text copy showing as  "New private group" instead of "New private channel" 
ER: Button text copy should be "New private channel"
Video/Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMzMzMF8yMTcwMjczNQ

**Comment by reyamir** [comment]
will be updated in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
