### ISSUE TITLE
Settings: Manage Relays: For the Connected relay, the textcopy is showing 'alway' instead of 'always'

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#312]
"1. Open the Arcade app on Android
2. Go to Settings>> Manage Relays
3. The Relay Manager screen will display and check the textcopy below the Connected header

AR: For the Connected relay, the textcopy is showing 'alway' instead of 'always'
ER: For the Connected relay, the textcopy should display 'always' instead of 'alway'
Video/Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMzc2Nl8yMTcwMzI2Mg

**Comment by reyamir** [comment]
will be updated in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
