### ISSUE TITLE
Login: The default text is not correct on the login page

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#313]
"1. Open the Arcade app on Android
2. Check the default text on login page"

AR: The default text is not correct on the login page, It should be Nsec or Pub key
ER: The default text in login page should shown correctly
Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxMzk2Ml8yMTcwMzUwNQ

**Comment by reyamir** [comment]
ah, it is correct
pubkey is not use to login
only nsec or private key (hexstring), you can read more about nsec here https://github.com/nostr-protocol/nips/blob/master/19.md
