### ISSUE TITLE
Contacts :  User able to add own profile in contacts 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#315]
"1. Open the Arcade app on Android
2. Go to User setting & tap on the npub code to copy it
3. Go to ""Contacts"" screen 
4.  Add New contact by tapping on ""+"" icon
5.  Add contact prompt will appear , just add npub code in it 
6.. click on ""Add"" button & check your own profile shown in contacts 

AR: User able to add own profile in contacts 
ER: User should not add own profile in contact screen

https://github.com/ArcadeLabsInc/arcade/assets/5452850/6002f2f6-007f-4ab4-b193-9dbee4e28b6e

**Comment by reyamir** [comment]
haha, this is a feature
