### ISSUE TITLE
Channel Manager :  "No About" text copy shown below the Channel name instead of "No Description"

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#326]
1. Open the Arcade app on Android 
2. Create some channels having No description  
3. On homepage, tap on the hamburger menu 
4. Go to Channel Manager screen
5. Check below channel name ""No About"" copy is showing 

AR: "No About" text copy shown below the Channel name instead of "No Description"
ER: Channel doesn' have description should display the text copy "No Description" in Channel Manager.
Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQxNzUyM18yMTcwODM4NA

**Comment by reyamir** [comment]
will be updated in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Verified in latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5527270114

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
