### ISSUE TITLE
Login: Update default text in access key field to " nsec or hexstring(private key)..." 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#329]
1. Open Arcade
2. Go to Login page
3. Check the copy is "nsec or hexstring..."

ER: It should be " nsec or hexstring(private key)..." 
![nsec](https://github.com/ArcadeLabsInc/arcade/assets/5452850/cc7bfaf3-832a-4a32-9df5-1c3cd5dc7857)

**Comment by reyamir** [comment]
will be updated in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Verified in latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5527270114
