### ISSUE TITLE
Contacts: Alert copy for invalid npub is not correct

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#330]
1. Open the Arcade app on Android
2. Go to User setting & tap on the npub code to copy it
3. Go to the ""Contacts"" screen 
4. Drag the modal to top
5.  Add New contact by tapping on the ""+"" icon
6.  Add contact prompt will appear, tap on the add npub code field and add some text in it.
7. Alert will appear and notice the alert copy.

AR: Getting Alert " Invalid contact: Error: can't resolve<entered text>"
ER: Input text should be "Invalid nPub for contact"

https://github.com/ArcadeLabsInc/arcade/assets/5452850/c842ecd7-20c5-4639-b2ea-943b19803a11

**Comment by reyamir** [comment]
will be updated in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
