### ISSUE TITLE
Channel: Member page: "Private group" text copy is showing instead of "Private channel"

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#340]
1. Open the Arcade App on Android
2. Go to any private channel created by user himself
3. Click on add member icon
4. Check  the subtitle

AR: Private group is displaying instead of private channel
ER: It should display private channel as user created channel from home page
Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQyNDQ1Ml8yMTcxOTMyMQ

**Comment by reyamir** [comment]
will be updated in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Not fixed, please reopen it.
