### ISSUE TITLE
AI Chat:   AI Chat  functionality is not working properly

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#343]
1. Open the Arcade App on Android as a logged in user
2. On homepage, open the New chat screen by tapping the ""+"" icon at top
4. Tap on ""New AI chat"" button
5. Send a message ex: ""Can you tell me today's date""
6. Check time stamp beside the message is not showing

AR: AI Chat functionality is not working properly
ER: AI Chat functionality should work properly 

https://qatester-mailinator.tinytake.com/msc/ODQyNDczNV8yMTcxOTY3OQ

**Comment by earonesty** [comment]
that is the correct date.   ai does not have access to new information.   only as of the training date.

**Comment by vikas1809** [comment]
@earonesty  Thanks for the info.
