### ISSUE TITLE
Contact: Adding contact without profile image, also not displaying default image holder

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#345]
1. Open the Arcade App on Android
2. Go to contact page, click (+) icon
3. Select any contact without profile image from suggestion
4. Again go to contact page, notice default image holder also missing from user profile

AR: Adding contact without profile image, also not displaying default image holder
ER: Default image holder should display, if user doest not have profile image set

https://qatester-mailinator.tinytake.com/msc/ODQyNDgzOF8yMTcxOTgxMg

**Comment by reyamir** [comment]
fixed in #351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
