### ISSUE TITLE
Channels: The Search box to enter 'Channel name' is missing from Channels Page

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#346]
1. Open the Arcade App on Android
2. Go to the Channels Page 
3. Notice the search box to enter the 'Channel name' or 'hex ID' is missing 

AR: The Search box to enter 'Channel name' or 'hex ID' is missing from Channels Page
ER: The Search box should display on the Channels Page
Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQyNDEwOF8yMTcxODg4Mw

**Comment by reyamir** [comment]
we not have search function yet, but better have in future

**Comment by reyamir** [comment]
dup #358

**Comment by vikas1809** [comment]
ok got it.
