### ISSUE TITLE
Homepage: Opening the 'Global Trade' & 'Arcade Feedback' channels are not showing any message

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#347]
1. Open the Arcade App on Android
2. On the Homepage, tap on the 'Global Trade' channel and no message displays
3. Similarly, go to the 'Arcade Feedback' channel and no message displays there too

AR: Opening the 'Global Trade' & 'Arcade Feedback' channels are not showing any message
ER: Opening the 'Global Trade' & 'Arcade Feedback' channels should display the previous messages
Video: https://qatester-mailinator.tinytake.com/msc/ODQyOTE1MV8yMTcyNTY3NQ

**Comment by reyamir** [comment]
fixed in latest build

**Comment by vikas1809** [comment]
Verified on the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5527270114
