### ISSUE TITLE
Settings: Manage Relays: On the 'Relay Manager' Page, the dialog box is disappearing on tapping the 'Relay URL' field 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#348]
1. Open the Arcade App on Android
2. Go to the ' Manage Relays' section under the 'Settings'
3. The 'Relay Manager' Page will open and tap on the '+' icon to add relay
4. The 'Add custom relay' will appear & check the dialog box disappears as soon as user taps on the Relay URL field

AR: On the Relay Manager Page, the dialog box is disappearing on tapping the 'Relay URL' field
ER: On the Relay Manager Page, the dialog box should not disappear on tapping the 'Relay URL' field
Video: https://qatester-mailinator.tinytake.com/msc/ODQyOTQ3Nl8yMTcyNjExMw

**Comment by reyamir** [comment]
oh, it react-native-bottom-sheet bug: https://github.com/gorhom/react-native-bottom-sheet/issues/1356

**Comment by reyamir** [comment]
fixed in #351

**Comment by vikas1809** [comment]
Working fine in the latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5533723105
