### ISSUE TITLE
Homepage :  The homepage displays ""No name"" when a user sends a direct message to another user.

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#349]
"1. Open the Arcade App on Android 
2. Go to Contact screen and add a contact 
3. Open the Profile of the user and send a direct mesage 
4. Go to homepage and check the user name displayed as ""No name"" 

AR: The homepage displays "No name" when a user sends a direct message to another user.
ER: User name should display 
Video:  https://qatester-mailinator.tinytake.com/msc/ODQyOTUyOV8yMTcyNjE2Nw

**Comment by vikas1809** [comment]
@reyamir Now name of own profile user is coming instead of the profile whom we are messaged. Can you please reopen it.

**Comment by reyamir** [comment]
oh, it fine with me, can you send me some screenshots or video

**Comment by reyamir** [comment]
fixed in https://github.com/ArcadeLabsInc/arcade/pull/351

**Comment by vikas1809** [comment]
Here you go with a video, https://QAtest.tinytake.com/msc/ODQ0MTI1M18yMTc0MTI5Mg
