### ISSUE TITLE
Profile :   The Copy link button next to the npub code is missing

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#350]
1. Open the Arcade App on Android as a logged in user
2. Tap on setting link, User profile will appear
3. Check there is no copy link button to copy the npub code 

AR: The Copy link button next to the npub code is missing
ER: There should be a copy button and when user tap on, it should change to copied 
Screenshot:https://qatester-mailinator.tinytake.com/msc/ODQyOTcyMl8yMTcyNjM2MQ

**Comment by earonesty** [comment]
if you click on it, it should copy though, right?

**Comment by vikas1809** [comment]
Fixed and verified on : https://github.com/ArcadeLabsInc/arcade/actions/runs/5546928322
