### ISSUE TITLE
Login: The loader keeps on spinning even after the alert message appears on editing the entered 'Hex' or 'Nsec' key

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#352]
1. Open the Arcade App on Android
2. Go to the 'Backup' settings and copy either the 'Hex' or the 'Nsec' key
3. Go back to the 'Settings' Page and tap on 'Logout' button 
4. Now, tap on the 'Login' button and enter the copied key
5. Try to edit the key and check the alert message appears correctly 
6. Close the alert message and notice the loader is still moving

AR: The loader keeps on spinning even after the alert message appears on editing the entered 'Hex' or 'Nsec' key
ER: The loader should not display after the alert message appears on editing the entered 'Hex' or 'Nsec' key

https://qatester-mailinator.tinytake.com/msc/ODQzMDQ0N18yMTcyNzI0Mg

**Comment by reyamir** [comment]
duplicate with #302 
will fixed in #351

**Comment by vikas1809** [comment]
Fixed and verified on : https://github.com/ArcadeLabsInc/arcade/actions/runs/5546928322
