### ISSUE TITLE
Channel/Direct message: User should be able to reply on particular thread

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#365]
Currently user is not able to reply on particular thread of message in direct message and channel 
There should be option so that user can reply on particular message thread.

**Comment by reyamir** [comment]
we've reply feature now, you can retest it

**Comment by reyamir** [comment]
added in #338

**Comment by vikas1809** [comment]
Fixed, verified in the build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5618484429
