### ISSUE TITLE
Chat: The chat messages overlap each other for a second while loading the group chat.

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#369]
1. Open the Arcade App on Android as a logged-in user
2. Go to the Home screen
3. Open any group chat and notice the overlapping of chat while loading the chat.

AR: The chat messages overlap each other while loading on the user's screen.
ER: The user should see the chat messages load and appear on the screen clearly and without any distortion or overlap.
Video: https://qatester-mailinator.tinytake.com/msc/ODQ0MDcwNV8yMTc0MDU2MA

**Comment by reyamir** [comment]
look like flashlist bug

**Comment by vikas1809** [comment]
Fixed, Verified in build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5583163026
