### ISSUE TITLE
Channels: Multiple private groups can be made with the same name.

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#370]
1. Open the Arcade App on Android as a logged-in user
2. Go to the Home screen
3. Tap on add button on the top right corner of the screen.
4.Tap on the new private group and create a name to the group for eg : uchiha
5 Repeat the 3 to 4 step again and notice the both the group chat name.

AR: Multiple private groups can be made with the same name.
ER:The user should not able to make multiple groups with the same name.
Video/Screenshot:https://qatester-mailinator.tinytake.com/msc/ODQ0MDk4NF8yMTc0MDk5Mg

**Comment by reyamir** [comment]
this is fine with nostr

**Comment by vikas1809** [comment]
ok got it, thanks for the info.
