### ISSUE TITLE
Notification: User is not receiving any notification message

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#373]
1. Open the Arcade App on Android.
2. Check the last message and go to profile
3. turn on the notification setting and update
4. Come back to Channel page and check for new messages
5. Notice user didn't received any notifification

AR: User is not receiving any notification message
ER: User should get notify about new messages
Video: https://qatester-mailinator.tinytake.com/msc/ODQ0Mjg2NV8yMTc0MzIxNA

**Comment by reyamir** [comment]
dup #172

**Comment by vikas1809** [comment]
OK thanks
