### ISSUE TITLE
New Channel: The 'Tick' symbol positioning is not proper

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#375]
1. Open the Arcade App on Samsung Mobile
2. On the Home screen, go to Channels and tap the ""+"" icon to create a New Channel
3. On the 'New Channel' page, notice the position of the 'Tick' symbol is displaying at extreme right top side

AR:The position of the 'Tick' symbol is not proper
ER:The position of the 'Tick' symbol should be proper
Screenshot:  https://qatester-mailinator.tinytake.com/msc/ODQ0NjEzN18yMTc0NzU2Mg

**Comment by reyamir** [comment]
updated in #384

**Comment by vikas1809** [comment]
Fixed, verified in the build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5618484429
