### ISSUE TITLE
AI chat: Mic icon is not responding

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#376]
1. Open AI chat window
2. Tap on mic icon
3. Nothing happens

![image](https://github.com/ArcadeLabsInc/arcade/assets/5452850/f76326f2-347c-4f5d-a521-e8c7b79693f6)

**Comment by reyamir** [comment]
fixed, but AI stuffs still in wip, maybe have other change

**Comment by vikas1809** [comment]
Verified in https://github.com/ArcadeLabsInc/arcade/actions/runs/5657361225
