### ISSUE TITLE
AI Chat: There is no padding space between the AI text and the text field

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#379]
1. Open the Arcade App on the Android
2. Go to the Home screen and go to any group i.e. The Lobby 
3. Check the padding space between the chats and the text field.
4. Now open an AI chat and notice the padding space between the AI text and the text field

AR: No padding space between the AI and the text field.
ER: There should be a padding space between the AI text and the text field.

https://qatester-mailinator.tinytake.com/msc/ODQ0NzYxMl8yMTc0OTM0NQ

**Comment by reyamir** [comment]
AI design isn't final yet

**Comment by vikas1809** [comment]
Got it
