### ISSUE TITLE
iOS: Settings: The 'Notifications' setting is not clickable

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#380]
1. Open the Arcade App on the iOS
2. Go to the Settings and tap on the 'Notifications' setting
3. Notice the user stays on the same screen instead of getting redirected to the 'Notifications' screen

AR: The 'Notifications' setting is not clickable
ER: The 'Notifications' setting should be clickable as in Android

https://qatester-mailinator.tinytake.com/msc/ODQ1MjI4NF8yMTc1NjM5MA

**Comment by reyamir** [comment]
notification isn't available in ios yet, but we should hide it instead of make it not clickable

**Comment by reyamir** [comment]
dup #410
