### ISSUE TITLE
iOS: Settings: Manage Relays: On the 'Relay Manager' screen, the textcopy is showing 'alway' instead of 'always' for the Connected relay

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#381]
1. Open the Arcade app on the iOS
2. Go to Settings>> Manage Relays
3. The Relay Manager screen will display and check the textcopy below the Connected relay

AR: For the Connected relay, the textcopy is showing 'alway' instead of 'always'
ER: For the Connected relay, the textcopy should display 'always' instead of 'alway' as it shows on Android

https://qatester-mailinator.tinytake.com/msc/ODQ1MjQzNF8yMTc1NjU4Ng

**Comment by reyamir** [comment]
fixed, but ios version still not use latest commit yet
