### ISSUE TITLE
iOS: Settings: Sometimes alert message is appearing on the 'Privacy' screen while toggling the Direct message button

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#382]
1. Open the Arcade app on the iOS
2. Go to Settings>> Privacy
3. Try to toggle the 'Direct message' button and tap on the 'Update' button
4. Notice the Alert message ""Failed to save settings: send timed out"" appears sometimes

AR: Sometimes alert message is appearing on the 'Privacy' screen while toggling the Direct message button
ER: The Alert message should not appear and settings should get updated as it displays on the Android

https://qatester-mailinator.tinytake.com/msc/ODQ1MjQyM18yMTc1NjU3NQ

**Comment by reyamir** [comment]
alert in this case is fine, but we can improve ux by ask user try again later (maybe at this time user can't connect to relays)

**Comment by reyamir** [comment]
updated in #384

**Comment by vikas1809** [comment]
Fixed, verified in the build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5618484429
