### ISSUE TITLE
Sign-up: Invalid username can be taken as a username on the signup page and showing

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#387]
1. Open the Arcade app on android.
2. Tap on create account.
3. Enter invalid user name such as (.......) on the username field
4. Tap on continue and notice the response 

AR: Invalid username can be taken as a username on the signup page
ER: An error message should pop up when an invalid username is submitted.

https://qatester-mailinator.tinytake.com/msc/ODQ1MzgzNF8yMTc1ODI3OA

**Comment by reyamir** [comment]
haha, this is valid
nostr is less strict than other platform, user can put almost everything in their profile

current validate rule for username in arcade:
- letters (a-z) 
- numbers (0-9)
- dots (.)
- underscores (_)

**Comment by vikas1809** [comment]
ok thanks
