### ISSUE TITLE
Invite screen : The background behind the ""Done"" button is not blurry, giving the impression that the button is overlapping. 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#388]
1. Open the Arcade app on android
2. On homepage, create a new private channel 
3.When reached to Invite screen, check by scrolling up and down
4. Notice Done button feels likes overlapping with the contacts 

AR: The background behind the ""Done"" button is not blurry, giving the impression that the button is overlapping.
ER: Done” button should have transparent Blurred background

https://qatester-mailinator.tinytake.com/msc/ODQ1NzQ4OV8yMTc2MzEzMQ

**Comment by reyamir** [comment]
invite screen has new design in #384

**Comment by vikas1809** [comment]
Invalid bug
