### ISSUE TITLE
Contacts: Different names are showing for the same user on the 'Suggestions' Contact screen and the user profile

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#389]
1. Open the arcade App on Android
2. Go to the 'Contacts' screen and tap on '+' icon to open the 'Add contact' screen
3. Scroll down the suggestions and add the contact ""https://silent.link/""
4. Go back to the Contacts screen and open the same user profile
5. Tap on the 'Message' button to go to the direct chat and notice the name on the screen

AR: Different names are showing for the same user on the 'Suggestions' Contact screen and the user profile
ER: Common name should display for the same user on the 'Suggestions' Contact screen and the user profile

https://qatester-mailinator.tinytake.com/msc/ODQ1NzU1Nl8yMTc2MzI3Mg

**Comment by reyamir** [comment]
updated in #384
all users name will display according to this order
```
username -> if no username -> display name -> if no display name -> no name
```
