### ISSUE TITLE
Relay Manager: The Alert message text is inappropriate on adding a valid relay in the 'Add Custom Relay' 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#390]
1. Open the Arcade App on the Android
2. Go to Settings>> Manage Relays
3. The 'Relay Manager' screen will display and tap on '+' icon on the top-right side
4. The 'Add custom relay' dialog box will open and enter a valid relay from the suggested relays lists
5. Notice the alert message appears with the incorrect text "Relay must be use websocket protocol, please check again"

AR: The Alert message text is inappropriate on adding a valid relay in the 'Add Custom Relay'
ER: The Alert message text should be grammatically correct on adding a valid relay in the 'Add Custom Relay'
Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQ1MjA2Nl8yMTc1NjEzOQ

**Comment by reyamir** [comment]
updated to text "Relay must use websocket protocol (start with wss:// or ws://), please check again" in #366

**Comment by vikas1809** [comment]
Fixed, verified in the build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5618484429
