### ISSUE TITLE
Homepage: The 'Left Out' Channel is displaying again when the user login through 'Nsec' or 'Hex' private key 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#391]
1. Open the Arcade App on the Android
2. Create a Channel and eventually Leave it
3. Return to the home screen and notice the same channel is no longer displaying there
4. Go to the 'Backup' setting and copy the 'Nsec' or 'Hex' private key
5. Tap on the ""Logout' button and re-login with the copied private key
6. On the Home screen, notice the left out channel again appears
 
AR: The 'Left Out' Channel is displaying again when the user login through 'Nsec' or 'Hex' private key
ER: The 'Left Out' Channel should not display again when the user login through 'Nsec' or 'Hex' private key
Video: https://qatester-mailinator.tinytake.com/msc/ODQ0NjUxMV8yMTc0ODAxNQ

**Comment by reyamir** [comment]
fixed #384

**Comment by vikas1809** [comment]
Fixed, verified in the build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5618484429
