### ISSUE TITLE
Home Screen: For the 'Global Trade' Channel, the previous messages are not displayed

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#393]
1. Open the Arcade app on Android
2. On the Home screen, tap on the 'Global Trade' channel 
3. The Channel screen will display and notice the previous messages are not appearing

AR: For the 'Global Trade' Channel, the previous messages are not displayed
ER: For the 'Global Trade' Channel, the previous messages should display
Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQ1ODcwOF8yMTc2NDgwNA

**Comment by reyamir** [comment]
until #395 is supported, we only load 500 latest messages now

**Comment by vikas1809** [comment]
Verified on latest build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5594827222
