### ISSUE TITLE
Channel: There is no option to change the profile pic , rename the channel name or see the member of the channel

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#396]
"1. Open the Arcade App on Android as a logged-in user
2. Go to the Home screen
3. Tap on add button on the top right corner of the screen.
4.Tap on the new private group and create a name for the group.
5 Now open the group and notice the option for change the profile pic, name or to see the group members "

AR: There is no option to change the profile pic , rename the channel name or see the member of the channel
ER: There should be an option to update the profile pic name of the channel and to see the members of the group.
Video: https://qatester-mailinator.tinytake.com/msc/ODQ2MjY0N18yMTc2OTgyNw

**Comment by reyamir** [comment]
dup #287

**Comment by vikas1809** [comment]
Got it.
