### ISSUE TITLE
Channel Chat screen :   User able access phone media even the Files and media permission is denied 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#399]
1. Go to  Arcade app info from your Phone settings 
2. Deny the permission of ""Files and media"" 
3. Open the Arcade app and go to any channel chat screen
4. Tap on ""Papper clip icon"" to send a document, image etc.
5. Check even permission denied user able to access file manager on your phone

AR: "User able access phone media even the Files and mediapermission is denied
ER: User should get validation message "Allow Arcade to access photos and media on your device
Video:  https://qatester-mailinator.tinytake.com/msc/ODQ2MjY3NV8yMTc2OTg1NQ

**Comment by reyamir** [comment]
in android 13, photo picker not required permission, but photos only (not files)
file and media permission not effect to photo picker
