### ISSUE TITLE
Arcade Feedback: Initially the 'No name' displays when the user messages to self or to a different user 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#403]
1. Open the Arcade App on the Android
2. Go to Home screen and open the 'Arcade Feedback' channel
3. Enter a message and reply using the same user
4. Hard close the app and reopen it 
5. Check the 'no name' displays for a short duration and 'Can't fetch event' displays for the message

AR: The 'No name' displays for short duration initially when the user messages to self or to a different user
ER: No name' should not display when the user messages to self or to a different user

https://qatester-mailinator.tinytake.com/msc/ODQ2MzQ0NV8yMTc3MDg4OQ

**Comment by reyamir** [comment]
updated in #433, no name also mean app can't fetch user's profile or it take long time to load

**Comment by vikas1809** [comment]
We need to hard close the app to see name else no name is appearing
