### ISSUE TITLE
Contacts :   Header text displayed as ""Direct Message"" while sending a message in such scenario 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#404]
1. Open the Arcade App on the Android as a logged in user
2. Go to User profile and keep the ""Display Name and Username"" fields blank 
3. Update it and check profile showing ""No name"" 
4. Copy the npub code and add it to contact on another device 
5. On Contacts screen go to profile and tap on ""Message"" button
6. Check the Header text shown as ""Direct Message"" 

AR: Header text displayed as ""Direct Message""  while sending a message in such scenario
ER: ""Display Name and Username"" both fields should set as Mandatory fields

https://qatester-mailinator.tinytake.com/msc/ODQ2MzY5M18yMTc3MTEzOA

**Comment by reyamir** [comment]
it seem weird but totally fine in Nostr, user don't need to set anything in profile
other nostr client instead of display "No name" or no avatar, they auto generated name for user, maybe we can add this feature in future

**Comment by vikas1809** [comment]
ok got it.
