### ISSUE TITLE
New Chat: Tapping on the 'Recent contacts' is showing the user name as 'Direct message' on the Chat screen

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#405]
1. Open the Arcade App on the Android
2. Add some new contacts and return to the Home Screen
3. Tap on the '+' icon to open the 'New Chat' screen
4. Tap on any added 'Recent contacts' and check the 'Direct Message' is displaying instead of the specific user name

AR: Tapping on the 'Recent contacts' is showing the user name as 'Direct message' on the Chat screen
ER: Tapping on the 'Recent contacts' should display the username correctly as it displays through the user Profile

https://qatester-mailinator.tinytake.com/msc/ODQ2NDAzMV8yMTc3MTczMA

**Comment by reyamir** [comment]
updated in #457
