### ISSUE TITLE
Recent contacts: The user is not able to send the message to the contacts in the recent contact list

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#406]
1. Open the Arcade App on the Android.
2. Go to the Home screen.
3. Tap on the '+' icon to open the 'New Chat' screen
4. Tap on any added 'Recent contacts' try to send message and notice the response.

AR: The user is not able to send the message to the contacts in the recent contact list , the send button is unresponsive.
ER: The user should able to send the message to the contacts in the recent contact list by tapping the send button.

https://qatester-mailinator.tinytake.com/msc/ODQ2NDAxM18yMTc3MTY5OA

**Comment by reyamir** [comment]
cause by same error in #420
