### ISSUE TITLE
Add Contact: The Alert message on re-adding the already added contact is showing incorrect text

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#407]
1. Open the Arcade App on the Android
2. Go to the 'Contacts' screen>> 'Add contact' 
3. The 'Add contact' modal will appear and enter a 'public key' or 'npub' to add the contact
4. Tap the 'Add' button and the contact is added to the 'Contacts' list
5. Again go to 'Add contact' screen, add the same contact through 'public key' or 'npub' and notice the alert message

AR: The Alert message on re-adding the already added contact is showing incorrect text
ER: The Alert message should be 'Contact has been added already'

https://qatester-mailinator.tinytake.com/msc/ODQ2NDAzOV8yMTc3MTczOQ

**Comment by reyamir** [comment]
updated in #401

**Comment by vikas1809** [comment]
Verified in build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5654100311
