### ISSUE TITLE
iOS: Settings: The 'Notifications' section is missing from the 'Settings' screen

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#410]
1. Open the Arcade App on the iOS
2. Tap on the Settings icon to open the 'Settings' screen
3. Scroll down the settings and notice the 'Notifications' section is not displayed

AR: The 'Notifications' section is missing from the 'Settings' screen
ER: The 'Notifications' section should display as it appears on the Android.
https://qatester-mailinator.tinytake.com/msc/ODQ2ODQzMV8yMTc3Nzc3NQ

Screenshot/Video : https://qatester-mailinator.tinytake.com/msc/ODQ2ODQzNV8yMTc3Nzc3OQ

**Comment by reyamir** [comment]
notification not support in ios yet, #172
