### ISSUE TITLE
Home Screen: The 'Channels' are not loading on the Channels screen

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#411]
1. Open the Arcade App on the Android/iOS
2. Go to the Home screen and tap on the Hamburger Menu on the top left corner
3. Open the Channels screen and notice the 'Loading' is displayed without any channels appearance

AR: The 'Channels' are not loading on the Channels screen
ER: The various 'Channels' should load on the Channels screen

https://qatester-mailinator.tinytake.com/msc/ODQ2ODQ0NF8yMTc3Nzc4OA

**Comment by reyamir** [comment]
it's fine, channel list is really huge, it take a bit time to load, but it should show loading indicator instead of "loading..." text

**Comment by vikas1809** [comment]
Not fixed still getting "loading..." text instead of loading indicator. Please reopen it.

**Comment by reyamir** [comment]
not push yet, still in this pr https://github.com/ArcadeLabsInc/arcade/pull/401
