### ISSUE TITLE
Home Screen: The messages are taking relatively longer time to update on the 'Arcade Feedback' Channel 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#412]
1. Open the Arcade App on the Android/iOS
2. Go to the Home screen and tap on the 'Arcade Feedback' channel
3. Enter a message on the Channel screen and it gets updated on the chats
4. Now, go back to the Home screen and check for the entered message
5. Refresh the screen and check the duration for message to display is quite longer

AR: The messages are taking relatively longer time to update on the 'Arcade Feedback' Channel
ER: The messages should update instantly on the Home screen too as it does on the Chat screen

https://qatester-mailinator.tinytake.com/msc/ODQ2ODY5MV8yMTc3ODEwOA

**Comment by reyamir** [comment]
updated in #433

**Comment by vikas1809** [comment]
Now the Message gets disappear after some time. 

https://github.com/ArcadeLabsInc/arcade/assets/5452850/85f15f48-0c6f-4516-bedc-f5f3b6bea1fd
