### ISSUE TITLE
Edit Profile: The 'Username' field is missing the asterisk icon 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#414]
"1. Open the Arcade App on the Android/iOS
2. Tap on the 'Create Account' button to open the 'Create account' screen
3. Notice the Username field is showing the asterisk icon
4. Fill in all the details and tap on the 'Continue' button to create an account
5. Go to the Settings>> Edit Profile
6. Notice the 'Username' field is missing the asterisk icon

AR: The 'Username' field is missing the asterisk icon
ER:   The 'Username' field should display the asterisk icon on the 'Edit Profile' screen too as it shows on 'Create Account' screen
Video: https://qatester-mailinator.tinytake.com/msc/ODQ2ODUzMV8yMTc3NzkzMw

**Comment by reyamir** [comment]
user can remove their username, we only require username on create account screen (to create nip05), after that user can remove or update it
