### ISSUE TITLE
User Profile: Going to the profile of an added contact with long name is displaying the name in trimmed form

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#415]
"1. Open the Arcade App on the Android/iOS
2. Go to the 'Contacts' screen and add any contact with long name eg. 'sparklingriver262@getalby.com'
3. The contact gets updated to the Contacts list and tap on it to open its Profile
4. Tap on the 'Message' button to open the direct chat screen and notice the name getting cropped from left side"

AR: Going to the profile of an added contact with long name is displaying the name in trimmed form
ER: The Long Name should display in ellipses to avoid the trimming
Screenshot: https://qatester-mailinator.tinytake.com/msc/ODQ2OTA1MV8yMTc3ODU2MA

**Comment by reyamir** [comment]
updated in #433

**Comment by vikas1809** [comment]
Verified in https://github.com/ArcadeLabsInc/arcade/actions/runs/5657361225
