### ISSUE TITLE
Profile: The contact settings section is getting squeezed 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#418]
"1. Open the Arcade App on the Android/iOS
2. Go to the contacts screen and then go to any user's profile
3. Tap unfollow button and then the private follow button.
4. Check the contact settings section

AR: The contact settings section is getting squeezed after tapping the private follow button.
ER: The contact settings section should not  get squeezed
Video: https://qatester-mailinator.tinytake.com/msc/ODQ2OTY5OF8yMTc3OTM1Nw

**Comment by reyamir** [comment]
updated in #433, instead of hiding disable element, it will show disable element but with help text eplain about it
