### ISSUE TITLE
Add Contacts: The scroll bar is overlapping with the "add"  button

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#419]
"1. Open the Arcade App on the Android/iOS
2. Go to the contacts screen and tap on the ""+"" icon.
3. On the add contacts screen scroll up the screen.
4. Notice the scroll bar and the add button"

AR: The scrollbar is overlapping with the "add" button
ER: The scrollbar should not overlap with the "add" button
Video: https://qatester-mailinator.tinytake.com/msc/ODQ2OTg4MF8yMTc3OTU1NQ

**Comment by reyamir** [comment]
updated in #433
