### ISSUE TITLE
Channel Manager: On the Invite Screen, the confirmation text is grammatically incorrect while inviting an added contact

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#424]
"1. Open the Arcade App on the Android/iOS
2. Add a contact to the Contacts list and go to the Channel Manager
3. Tap on the 'Invite' icon for any channel eg. Arcade Feedback, the added contact will display
4. Tap on the contact to select and press the 'Enter' icon
5. The Confirmation text ""Confirm choose those selected contacts"" appears  

AR: The Confirmation text is grammatically incorrect as 'choose' is showing instead of 'choosing' in the displayed text
ER: On the Confirmation text word 'choose' should be replaced by 'choosing' to make it grammatically correct
Video:  https://qatester-mailinator.tinytake.com/msc/ODQ3Mzk5N18yMTc4NDc1Ng

**Comment by reyamir** [comment]
updated in #433
