### ISSUE TITLE
Profile: The created account profile is displayed again although the user has already logged out from that account

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#426]
"1. Open the Arcade App on the Android/iOS as a logged in user
2. Go to the 'Backup' settings and copy either the 'Hex' or the 'Nsec' key
3. Tap on the Logout button And go to the 'Create Account' screen
4. Enter a username and go to the Profile to check the new account is displayed
5. Now, tap on the Logout button and go to the 'Login' Page 
6. Enter the copied key and check the profile of the user at the starting time displays
7. Close the App once, open it again and switch to 'Profile' to notice two different profiles are visible"

AR: The created account profile is displayed again although the user has already logged out from that account
ER: The Logged out user's profile should not display again
Video: https://qatester-mailinator.tinytake.com/msc/ODQ3NDYwNl8yMTc4NTU0NA

**Comment by reyamir** [comment]
updated in #433

**Comment by vikas1809** [comment]
Issue still exist.
