### ISSUE TITLE
Invite Screen :   When the add contact field is left empty, an incorrect message is displayed

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#428]
"1. Open the Arcade App on Android/iOS as a logged-in user.
2. Create a private channel 
3. On Invite screen, tap on (+) icon to add a new contact
4. Invite contact overlay will appear
5. Keep the field blank and tap on ""Add"" button 
6. Check validation message shown is incorrect 

AR: "When the add contact field is left empty, an incorrect message is displayed"
VR: The validation message should read, "Public key or npub is required" if the add contact field is left empty.
Video: https://qatester-mailinator.tinytake.com/msc/ODQ3NDkwM18yMTc4NTkxNw

**Comment by reyamir** [comment]
updated in #433

**Comment by vikas1809** [comment]
Still, issue exist when user add blank character and click on Add button.
![image](https://github.com/ArcadeLabsInc/arcade/assets/5452850/bf57b53c-6303-4c2f-aec0-729db5dfa058)

**Comment by reyamir** [comment]
this message is fine, no need to make seperate message for blank character, it make a bit complex
