### ISSUE TITLE
Contact setting: Sometime alert message is appearing on the contact setting while toggling on/off  the "Use legacy,Unblinded DM's" repeatedly

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#429]
"1. Open the Arcade App on Android/iOS as a logged-in user.
2.  Go to other user profile from contact page
3. Now, repeatedly toggle on/off for ""Use legacy,Unblinded DM's"" setting"

AR: Sometime alert message is appearing on the contact setting while toggling the "Use legacy,Unblinded DM's" repeatedly
ER: The alert message should not appear on toggling on/off setting repeatedly
Video: https://qatester-mailinator.tinytake.com/msc/ODQ3NDkxMV8yMTc4NTkyNQ

**Comment by reyamir** [comment]
alert in this case is fine, when user click multiple time, it will cause rate-limited from relay
