### ISSUE TITLE
Profile screen :    Changes made to the user profile don't save quickly, needs to reopen the app again

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#430]
"1. Open the Arcade App on Android/iOS as a logged-in user.
2. Go to User profile and edit it 
3. Update the profile and check profile not get updated instantly
4. Close the app and open it again
5. Go to Profile and check now profile is updated 

AR: "Changes made to the user profile don't save quickly,needs to reopen the app again"
ER: Any changes made to the user profile should appear right away
Video: https://qatester-mailinator.tinytake.com/msc/ODQ3NDg4OF8yMTc4NTkwMg

**Comment by reyamir** [comment]
updated in #433

**Comment by vikas1809** [comment]
Working fine in the build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5657361225
