### ISSUE TITLE
Home Page: Sometimes App crashed message is displayed

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#432]
"1. Open the Arcade App on iOS 
2. Try to switch between Home screen, Contact Screen or the Settings screen
3. Notice the App crash message flashes sometimes

AR: Sometimes App crashed message is displayed
ER: App should load properly and crashed message should not display
Video:  https://qatester-mailinator.tinytake.com/msc/ODQ4MTMzNl8yMTc5NTE5Nw

**Comment by reyamir** [comment]
cause by same error in #421
