### ISSUE TITLE
Channel- "Invite by pub key" heading and subheading are getting cropped 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#437]
"1. Open the Arcade App on the Android (Samsung F12)
2. On the home page tap on the ""+"" icon on the top left cornor.
3. Try to make any channel private or public.
4. On the invite screen tap the""+"" icon.
5. When Invite by pubkey prompt displays drag it up and tap on the entry field.
6. Notice the screen.

AR: The "Invite by pub key" heading and subheading are getting cropped after tapping on npub entry screen
ER: The "Invite by pub key" heading and subheading should not get cropped 
Video: https://qatester-mailinator.tinytake.com/msc/ODQ4MzcxN18yMTc5Nzk1OA

**Comment by reyamir** [comment]
fixed in #457

**Comment by vikas1809** [comment]
https://github.com/ArcadeLabsInc/arcade/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc
