### ISSUE TITLE
Login Screen: The 'Login' Header is missing at the top of the screen

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#438]
"1. Open the Arcade App on the Android/iOS
2. Tap on the 'Login' button and the Login Screen will appear with private key field
3. Notice the screen header is not appearing on the right side of 'back' arrow

AR: The 'Login' Header is missing at the top of the screen
ER: The 'Login' Header should display at the top of the screen as it does for 'Create Account' screen
Video: https://qatester-mailinator.tinytake.com/msc/ODQ4MzczNF8yMTc5Nzk3Ng

**Comment by reyamir** [comment]
it match original design

**Comment by vikas1809** [comment]
OK got it
