### ISSUE TITLE
"Channels Chat Screen:  When responding to a lengthy text message, the message is cut off at the beginning and does not use ellipsis.

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#442]
"1. Open the Arcade App on the Android/iOS
2. Go to the Home screen and open any channel eg. 'The Lobby'
3. The Channel chat screen will display and move to any lengthy message 
4. Scroll towards right over the message and notice the message get cut off and also not use ellipsis

AR: "When responding to a long text message, it shouldn't be cut off at the beginning and should use an ellipsis.
ER: "On replying to the length text message, It should not get cut off from the beginning and should come in ellipsis "
Video: https://qatester-mailinator.tinytake.com/msc/ODQ4NzQxN18yMTgwMjcyNw

**Comment by reyamir** [comment]
this is react native bug https://github.com/facebook/react-native/pull/36428 , we need to wait they provide fix
but android only
