### ISSUE TITLE
Contacts: "Something went wrong" error message appeared while sending a message to a particular  contact

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#448]
1. Open the Arcade App on the Android
2. From the home page go to the contacts screen
3. Tap on contact i.e AinsleyCostello
4. Go to the user's profile and try to send a message.
5. Notice the screen is displaying the error message.

AR: "Something went wrong" error message appeared after sending a message to a particular contact.
ER: The error message should not appear.

https://qatester-mailinator.tinytake.com/msc/ODQ4ODM2OV8yMTgwMzgwNA

**Comment by reyamir** [comment]
fixed in #457

**Comment by vikas1809** [comment]
This contact "AinsleyCostello" is not coming in new build.
Verified in https://github.com/ArcadeLabsInc/arcade/actions/runs/5689618185
