### ISSUE TITLE
Channel Manager: Channel gets disappear on refreashing

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#449]
1. Open the Arcade App on the Android
2. Click on hamburger menu and go to channel manager page
3. Refresh the page
4. Notice channel gets disappear on refreshing
5. Go to contacts
6. Refresh the page
7. Notice contacts gets disappear on refreshing

AR: Channel and contacts gets disappear on refreashing
ER: Channel and contacts should not gets disappear on refreshing, until user don't exit himself

https://qatester-mailinator.tinytake.com/msc/ODQ4ODY5OV8yMTgwNDI1Mg
https://QAtest.tinytake.com/msc/ODQ5MzA2NF8yMTgxMDA2MA

**Comment by reyamir** [comment]
this issue cause by publish joined channels to all relays failed (cause by rate-limited), so joined channels will disappear after user refresh

**Comment by reyamir** [comment]
fixed

**Comment by vikas1809** [comment]
Fixed, Verified in https://github.com/ArcadeLabsInc/arcade/actions/runs/5689618185
