### ISSUE TITLE
Profile Settings:  The user is not shown the default profile and cover pic on installing the app for the first time. 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#450]
1. Open the Arcade App on the Android for the first time
2. Tap to open the Setting icon on the bottom bar.
3. Notice the default profile pic and the cover image on the setting page

AR: The user is not shown the default profile and cover pic on installing the app for the first time.
ER: The user should be shown default profile and cover pic on installing the app for the first time. 

https://qatester-mailinator.tinytake.com/msc/ODQ5MjY4OF8yMTgwOTY1NQ

**Comment by reyamir** [comment]
it seem loading issue

**Comment by reyamir** [comment]
fixed

**Comment by vikas1809** [comment]
Fixed, Verified in https://github.com/ArcadeLabsInc/arcade/actions/runs/5689618185
