### ISSUE TITLE
Profile Settings: The header is missing on the profile setting screen 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#451]
1. Open the Arcade App on the Android.
2. Tap to open the Setting icon on the bottom bar.
3. Scroll the screen and notice the header 

AR: The header is missing on the profile setting screen.
ER: The header should be visible on the top of the screen and should be shown at the top while scrolling the screen

https://qatester-mailinator.tinytake.com/msc/ODQ5Mjc3M18yMTgwOTc2OA

**Comment by reyamir** [comment]
hmm, I can't reproduce, what kind of phone?

**Comment by vikas1809** [comment]
As discussed it is not an issue.
