### ISSUE TITLE
Invite by pubkey: Modal closes as soon user taps on it

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#452]
1. Create private channel
2. In the invite screen tap on + icon
3. Invite by pubkey modal opens
4. Tap on text box to add pubkey 
5. Modal closes

https://github.com/ArcadeLabsInc/arcade/assets/5452850/7dc3f720-8bd4-46fa-bbac-90e2a17813f8

**Comment by reyamir** [comment]
cause by same error in #437 , use this issue to track
