### ISSUE TITLE
Channels Screen: On leaving a channel on the Channels Screen, considerable delay is visible when compared it with the Home screen 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#454]
"1. Open the Arcade App on the Android
2. Go to the Home screen, tap on any channel eg. Arcade Feedback 
3. The Channel screen will open and tap on the 'CONFIRM' button to leave the channel
4. Notice the user is redirected to Home screen instantly
5. Now tap on the Hamburger Menu to open the Channels and leave any joined channel
6. Notice there is comparatively more delay on the Channels screen"

AR: On leaving a channel on the Channels Screen, considerable delay is visible when compared it with the Home screen
ER: On leaving a channel on the Channels Screen, there should be no delay and user should be redirected to previous screen instantly
Video:  https://qatester-mailinator.tinytake.com/msc/ODQ5NDE5M18yMTgxMTUwMQ

**Comment by reyamir** [comment]
same as #435 , when user leave channel, channel list is also reload, so it take a bit of time to load

**Comment by vikas1809** [comment]
Ok got it.
