### ISSUE TITLE
Channels: For the joined channels, the user is restricted to tap on the 'Joined' button to open the respective Channel

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#455]
"1. Open the Arcade App on the Android
2. On the Home Screen, tap on the Hamburger Menu to go to the Channels
3. For the channels already joined, try to tap on the Channel Name to open it
4. Notice the tapping on the 'Joined' button is only way to open the Channel"
 
AR: For the joined channels, the user is restricted to tap on the 'Joined' button to open the respective Channel
ER: For a joined channel, the user should be allowed to tap anywhere inside the Channel box to open it
Video: https://qatester-mailinator.tinytake.com/msc/ODQ5NTE3M18yMTgxMjY1MQ

**Comment by reyamir** [comment]
#457
