### ISSUE TITLE
Relay Manager: Alert message is appearing on adding a private key to 'Add custom relay' Modal

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#458]
1. Open the Arcade App on the Android
2. Go to the Settings>> Backup
3. Copy the private key and move to the 'Manage Relays' section
4. On the 'Add custom relay' Modal enter 'ws://' and paste the copied private key 
5. Notice the alert message appears on tapping the 'Add' button

AR: Alert message is appearing on adding a private key to 'Add custom relay' Modal
ER: "The private key should get added as relay as it happens on iOS
https://qatester-mailinator.tinytake.com/msc/ODUwMDA2OF8yMTgxODgyMA"

https://qatester-mailinator.tinytake.com/msc/ODUwMDA4M18yMTgxODg0OQ

**Comment by reyamir** [comment]
private key can't use to add relay, ios build is old, it not up to date with android
