### ISSUE TITLE
Channel Manager: On the Invite screen, there is no way to remove the 'Added' contact

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#459]
1. Open the Arcade App on the Android/iOS
2. Add some contacts to the Contact list and go to the Channel Manager
3. Tap any channel to add contacts and the Invite screen will open
4. Select any contact and press the enter arrow
5. Return to the same channel and notice the 'Added copy' displays with added contact
6. Tap on the 'Added' term and notice there is no way to remove the added contact

AR: On the Invite screen, there is no way to remove the 'Added' contact
ER: Returning to the Invite screen, the Added contact should be able to remove from the channel

https://qatester-mailinator.tinytake.com/msc/ODUwNDYxNl8yMTgyNDYyNg

**Comment by reyamir** [comment]
dup #283
