### ISSUE TITLE
Contact screen :   Padding space between the text and the ""OK"" button is slightly bigger

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#461]
1. Open the Arcade App on the Android
2. On Contact screen Add some contacts
3. Open any user profile. and Set ""Hide this contact"" toggle to yes 
4. Toggle ""Use legacy, unblinded Dm's"" will turned off 
5. Tap on the question mark icon next to the toggle 
6. Notice the padding space between the headline text and the ""OK"" button

AR: Padding space between the text and the "OK" button is slightly bigger 
ER: Padding space between the text copy and the "OK" button should be proper

https://qatester-mailinator.tinytake.com/msc/ODUwNDU1MV8yMTgyNDU2MA

**Comment by reyamir** [comment]
this is default android modal, we can't custom it
