### ISSUE TITLE
Home screen :   The chat header of own username is displayed instead of the user profile with the text sent 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#462]
1. Open the Arcade App on the Android
2. On Contact screen Add some contacts
3. Open any user profile. & Turn off the toggle ""Use legacy, unblinded Dm's"" 
4. Send the Message to the user
5. Noitce a chat header with your own username and the text you sent to the user appears on the home screen in place of the person's profile.

AR: The chat header with own username is displayed instead of the user profile with the text sent.
ER: Chat header of the user with the text sent should display on the Home screen

https://qatester-mailinator.tinytake.com/msc/ODUwNDY2NV8yMTgyNDY5MA

**Comment by reyamir** [comment]
Issue: unblinded dm not display exactly in home screen

**Comment by reyamir** [comment]
#457
