### ISSUE TITLE
Add contact: The remove button text is getting crop on the add contact screen.

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#464]
1 Open the Arcade App on the Android
2. On Contact screen, Tap on ""+"" button on the top.
3. Add contact screen will appear having suggested contacts.
4. Tap on add button on any contact and notice the remove button 

AR: The remove button text is getting crop on the add contact screen.
ER: The remove button text should be fully visible.

https://qatester-mailinator.tinytake.com/msc/ODUwNTE5NF8yMTgyNTMyNg

**Comment by reyamir** [comment]
dup #467
