### ISSUE TITLE
Relay Manager: The Suggested relays are not displaying 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#465]
1. Open the Arcade App on the Android/iOS
2. Go to Settings>> Manage Relays
3. The 'Relay Manager' screen will appear & notice the blank is displayed below the Suggested relays

AR: The Suggested relays are not displaying
ER: The Suggested relays should appear on the Relay Manager screen

https://qatester-mailinator.tinytake.com/msc/ODUwNTI2OV8yMTgyNTQwMQ

**Comment by reyamir** [comment]
#457
