### ISSUE TITLE
Contacts Screen: For the added contacts, the remove icon is getting cropped on the Contacts list

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#466]
1. Open the Arcade App on the Android
2. Go to the Contacts Screen>> Add contact and add some contacts
3. Return Back to the Contacts Screen and notice the 'Remove' icon is getting cropped 

AR: For the added contacts, the remove icon is getting cropped on the Contacts list
ER: The Remove icon should display correctly

https://qatester-mailinator.tinytake.com/msc/ODUwNTIwNl8yMTgyNTMzOA

**Comment by reyamir** [comment]
dup #467
