### ISSUE TITLE
Contact screen :   Contact ""remove"" button get shifted when switching off the toggle ""Use legacy, unblinded DM's""  button

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#467]
"1. Open the Arcade App on the Android
2. Go to the Contacts Screen>> Add contact and add some contacts
3. Return Back to the Contacts Screen and go to any user profile 
4. Turn off the toggle button "" ""Use legacy, unblinded DM's""  
5. Return back to contact screen and Notice remove contact button get shifted

AR: "Contact ""remove"" button get shifted when switching off  the toggle ""Use legacy, unblinded DM's"" button"
ER: Remove contact button should stay on its original position 
https://qatester-mailinator.tinytake.com/msc/ODUwNTIzOF8yMTgyNTM3MA

**Comment by reyamir** [comment]
#457
