### ISSUE TITLE
Channels Chat: For some messages on the current date, the date is showing instead of the time of the message

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#468]
1. Open the Arcade App on the Android
2. Go to the Home Screen and tap on the added channel 'Nostr'
3. The Channels chat will display and scroll up to visit the previous messages
4. Notice the some messages are showing today's date Jul 28 instead of the time of message sent

AR: For some messages on the current date, the date is showing instead of the time of the message
ER: For the present day the time of message sent should display
https://qatester-mailinator.tinytake.com/msc/ODUwNTQ5OV8yMTgyNTY2Mg

**Comment by reyamir** [comment]
this behavior copy from telegram, message older than 1 day will display as date
