### ISSUE TITLE
Contacts: The validation dialog box is not appearing while leaving/removing the added contacts as it displays for removing the added channels

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#469]
"1. Open the Arcade App on the Android
2. Tap on the Hamburger Menu and go to the Channel Manager
3. Tap on the remove icon on any added channel and notice the validation dialog box appears for confirmation
4. Return back to Home Screen and now go to Contacts Screen where some contacts are already added
5. Tap on the remove icon on any added contact and notice the contact gets removed without validation display

AR: The validation dialog box is missing on leaving/removing the contacts while it displays for removing the added channels
ER: The validation dialog box should display on leaving/removing the added contacts as it displays for removing the added channels
https://qatester-mailinator.tinytake.com/msc/ODUxMDMyMl8yMTgzMzI1Mw

**Comment by reyamir** [comment]
#457
