### ISSUE TITLE
Contacts: The Profile icon is not tappable on the added Contact lists

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#470]
1. Open the Arcade App on the Android
2. Go to the Contacts screen and tap on the '+' icon to open the 'Add contact' screen
3. Tap on the 'Add' button for some contacts on Suggestions and return back to the Contacts screen
4. Tap on the Profile icon against each added contact and notice nothing happens on tapping
5. Now, tap on the Contact name and notice the respective contact profile displays

AR: The Profile icon is not tappable on the added Contact lists
ER: The Profile icon should be tappable to lead to the respective contacts's profile screen
https://qatester-mailinator.tinytake.com/msc/ODUxMDMyN18yMTgzMzI1OA

**Comment by reyamir** [comment]
this is badge for contact that using legacy direct message, but we can add alert when user click to this icon to improve ux
#457
