### ISSUE TITLE
Channel Manager: No error message is displayed when the same public key or npub is entered multiple times on the 'Invite by pubkey' Modal

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#471]
"1. Open the Arcade App on the Android
2. Tap on the Hamburger Menu and Go to the Channel Manager
3. Tap on the 'Add member' icon on any channel and the Invite screen opens
4. Tap on the '+' icon to open the 'Invite by pubkey' Modal
5. Enter a valid public key and tap the 'Add' button
6. Notice the contact displays with the 'Added' copy
7. Now, enter the same public key once again & notice another contact displays with the 'Added' copy displays on the Invite screen

AR: No error message is displayed when the same public key or npub is entered multiple times on the 'Invite by pubkey' Modal
ER: The Error message should display to restrict the user from entering the same public key twice 
Video: https://qatester-mailinator.tinytake.com/msc/ODUxMDkwOF8yMTgzMzk1MA

**Comment by reyamir** [comment]
#457
