### ISSUE TITLE
Contact Screen :   When adding a contact by tapping the ""Add"" button, the user profile image changes 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#473]
1. Open the Arcade App on the Android
2. Go to Contact screen, tap on the (+) icon at right top corner 
3. Scroll down to contact: ""rasha22"" and tap on ""Add"" button
4. Check Profile image get changed 

AR: "When adding a contact by tapping the ""Add"" button,  the user profile image changes"
ER: User Profile image should get change when adding the contact 
https://qatester-mailinator.tinytake.com/msc/ODUxMDg4NV8yMTgzMzkyNw

**Comment by reyamir** [comment]
when fetch API (https://api.nostr.band/v0/trending/profiles) for suggestions, it will use embed contact's profile, which may be outdated
when user add/remove contact, it will refetch contact's profile, this time it will use latest profile
it's rare case, but seem fine
