### ISSUE TITLE
Profile Screen :   The user can leave the ""NIP-05"" field empty

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#474]
1. Open the Arcade App on the Android
2. Go to Setting screen, tap on the edit icon to edit the profile
3. Keep the ""NIP-05"" field blank and update it
4. Notice User able to keep the NIP-05 field blank 

AR: The user can leave the "NIP-05" field empty
ER: The "NIP-05" field should not be left blank
https://qatester-mailinator.tinytake.com/msc/ODUxMTM2NV8yMTgzNDQ4Mw

**Comment by reyamir** [comment]
this is fine, nip05 only required in create account step, after that, user can change to other service, or just remove it
