### ISSUE TITLE
Profile Screen :   When adding a Relay with a long string, the app crashes 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#475]
1. Open the Arcade App on the Android
2. Go to Setting screen, Tap on ""Manage Relays"" button
3. Add a new Relay by tapping the (+) icon at right corner
4. Enter the long string starts with ""ws://"" 
5 Tap on ""Add"" button 

AR: When adding a Relay with a long string, the app crashes
ER: App should not get crahsed when adding a long string relay 

https://qatester-mailinator.tinytake.com/msc/ODUxMTEwNF8yMTgzNDE3Ng

**Comment by reyamir** [comment]
this issue can simple fix by limit max length, but it make code more complex and we don't need to strict in this case

**Comment by vikas1809** [comment]
@reyamir  Crashing of the app is very unexpected so do we have any way to restrict it?
