### ISSUE TITLE
Contacts: The copy of the validation message is grammatically incorrect when the user tries to remove a contact from the contacts list

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#479]
1. Open the Arcade App on the Android
2. Go to the Contacts Screen and tap on the '+' icon to open the Add contact screen
3. Add some contacts and return back to the 'Contacts' screen
4. Tap on the remove icon on the added contacts and notice the validation message 'Confirm remove this contact' appears
5. The copy is incorrect as 'to' is missing between the 'Confirm' and 'remove'

AR: The copy of the validation message is grammatically incorrect when the user tries to remove a contact from the contacts list
ER: The correct copy should display on the validation message

https://qatester-mailinator.tinytake.com/msc/ODUxNzEzMV8yMTg0MTYxMQ

**Comment by reyamir** [comment]
updated, we can combine all grammar issues to one

**Comment by vikas1809** [comment]
Verified on build: https://github.com/ArcadeLabsInc/arcade/actions/runs/5736929368
