### ISSUE TITLE
Contact Screen :   The contact is added to the contact list after being unfollowed

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#482]
1. Open the Arcade App on the Android
2. On Contacts Screen, tap on the '+' icon to open the Add contact 
3. Scroll to any contact ex: james and open the profile
4. ""Unfollow"" it and return back to contact screen
5. Check contact ""james"" get added to contact 

AR: The contact is added to the contact list after being unfollowed
ER: Contacts should only be added to the contact list after the user taps the ""add"" button

https://qatester-mailinator.tinytake.com/msc/ODUxNzk1MV8yMTg0MjU3Ng

**Comment by reyamir** [comment]
unfollow action isn't process yet
this issue cause by user go back before unfollow action is done, when unfollow action is done the follow/private follow button will reappear again
