### ISSUE TITLE
Chat Screen :   In the conversation, the user is unable to send media/document files

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#483]
1. Open the Arcade App on the Android
2. On Home, Tap on any channel to open the chat screen
3. tap the paper clip icon to send images/media files
4. Notice user unable to send Docs or Media file 

AR: In the conversation, the user is unable to send media/document files
ER: The user should be able to send media and document files

https://qatester-mailinator.tinytake.com/msc/ODUxODAzMl8yMTg0MjY1Ng

**Comment by reyamir** [comment]
we only allow upload media at this time
