### ISSUE TITLE
Channels Screen: For a particular channel i.e. "uncomfortabletruths" the user's profile icon is missing on the chats

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#488]
"1. Open the Arcade App on the Android
2. From the home page, go to the channels screen.
3. Scroll down to the channel i.e. ""uncomfortabletruths"" 
4. Join the channel and notice on the chats the user's profile icon is missing.

AR: The user's profile icon is missing on the chats of a particular channel
ER: The user's profile icon should display.
https://qatester-mailinator.tinytake.com/msc/ODUyNzkwOF8yMTg1NTUxNw

**Comment by reyamir** [comment]
this user's avatar is black image
