### ISSUE TITLE
Channels Screen: Some channels are displayed without a channel name or description

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#489]
"1. Open the Arcade App on the Android
2. From the home page, go to the channels screen.
3. Scroll down on the channels screen and notice some channels will display without channel names or description

AR: Some channels are displayed without a channel name or description
ER: The channel name or description should display
https://qatester-mailinator.tinytake.com/msc/ODUyNzkzMl8yMTg1NTU0MQ

**Comment by reyamir** [comment]
channel's name and description are not required, user can create channel without any information (with other client)
