### ISSUE TITLE
Contact Screen :   The user can add a contact by using the Private (Hex) key 

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#491]
1. Launch the Arcade App on Android
2. Select ""Backup"" from the User Profile 
3. Copy the private key (Hex)
4. Switch to a different device and access the contact screen
5. Tap on the (+) symbol to add a contact, then paste the copied hex key into the invite modal
6. Take note that no error notice occurs
7. Open the Profile and look for the npub ID
8. Notice how the initial user's Nsec key is turned into a npub ID in the contact list of another device

AR: The user can add a contact by using the Private (Hex) key
ER: When adding a contact with the Private (Hex) Key, the user should see the same error message as when using the Nsec key 
https://qatester-mailinator.tinytake.com/msc/ODUyODQ5OF8yMTg1NjM0MQ

**Comment by reyamir** [comment]
hex private key has same format with public key, it will valid for this case
user should only use npub or nsec, we use hex private key just for maximum compatible with other client
