### ISSUE TITLE
Channel Manager:  On the Invite screen, tapping on the 'CANCEL' button on the validation message is not deselecting the selected contact

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#493]
"1. Open the Arcade App on the Android
2. Add some contacts to the Contacts list and go to the Channel Manager
3. Tap on 'Add member' icon on any channel eg. Arcade Feedback to open the Invite Screen
4. Tap on any contact and press the 'Enter' icon at the bottom of the screen
5. The validation message appears for Confirmation and choose the 'CANCEL' option
6. The message closes but the selected state is still appearing for the Contact name

AR: On the Invite screen, tapping on the 'CANCEL' button on the validation message is not deselecting the selected contact
ER: On the Invite screen, after tapping on the 'CANCEL' button on the validation message, the selected contact should no longer display in the selected state
https://qatester-mailinator.tinytake.com/msc/ODUyODQyM18yMTg1NjI1MQ

**Comment by reyamir** [comment]
if user just want to cancel for add one or two contacts, we don't need to clear all previous selections
