### ISSUE TITLE
Settings: The Account section is tappable

### ISSUE THREAD

**Issue by vikas1809** [ArcadeLabsInc/arcade#494]
"1. Open the Arcade App on the Android
2. Tap on the 'Settings' icon and move to the Account sections
3. Tap on the username, NIP-05 or About field and notice the user's edit profile displays
4. Tap on the 'Back' arrow at the top to return to user settings screen
5. Now, tap on the 'edit' icon to open the User Edit Profile screen"

AR: On the settings screen, the 'Account' section is tappable
ER: On the Settings screen, the user should be limited to opening the 'Edit Profile' screen by tapping the 'edit' icon only
https://qatester-mailinator.tinytake.com/msc/ODUyODQyOF8yMTg1NjI1Ng

**Comment by reyamir** [comment]
it is same behavior with telegram, user can click to account section to open edit screen
